### ISSUE TITLE
Native methods on interfaces or interface delegation?

### ISSUE THREAD

**Issue by AKJAW** [rickclephas/KMP-NativeCoroutines#35] opened 2022-02-04 07:52 UTC
Hello, our Kotlin Multiplatform project is modularized, where one feature has at lest 2 gradle modules: an API module that contains the interfaces and data structures, and an Implementation  module that contains the implementation details for the API module.

Currently we are using Kotlin / Native wrappers akin to [this](https://dev.to/touchlab/working-with-kotlin-coroutines-and-rxswift-24fa):
```kotlin
class FlowWrapper<T>(
    private val scope: CoroutineScope,
    private val flow: Flow<T>,
) {
    init {
        freeze()
    }

    fun subscribe(
        onEach: (item: T) -> Unit,
        onThrow: (error: Throwable) -> Unit,
    ): Job = subscribe(onEach, onThrow, {})

    fun subscribe(
        onEach: (item: T) -> Unit,
        onThrow: (error: Throwable) -> Unit,
        onComplete: () -> Unit,
    ): Job = flow
        .onEach { onEach(it.freeze()) }
        .catch { onThrow(it.freeze()) }
        .onCompletion { onComplete() }
        .launchIn(scope)
        .freeze()
}
```

[link](https://github.com/AKJAW/KMP-Natvie-Coroutines-Modularization-Issue/blob/3f0e587b5baa80e9ce5d93f8a0ae3ee9dbf630f6/kmm/todos/todos-count-api/src/iosMain/kotlin/co/touchlab/kmm/todos/count/api/domain/GetTodoCountIos.kt)
```kotlin
class GetTodoCountIos(
    private val getTodoCount: GetTodoCount
){

    fun invoke(): FlowWrapper<TodoCount> =
        FlowWrapper(
            scope = CoroutineScope(SupervisorJob() + Dispatchers.Main),
            flow = getTodoCount()
        )
}
```

Where GetTodoCount is an interface, and in swift this wrapper is used as **getTodoCount**:
[link](https://github.com/AKJAW/KMP-Natvie-Coroutines-Modularization-Issue/blob/3f0e587b5baa80e9ce5d93f8a0ae3ee9dbf630f6/ios/KaMPKitiOS/AppDelegate.swift)
```swift
getTodoCount.invoke().subscribe { count in
    if (count != nil){
        self.count = count as! TodoCount
    }
} onThrow: { KotlinThrowable in
    
}
```

## Removing the wrapper

When trying this library out I was unable to use the interface abstraction on iOS. I removed the GetTodoCountIos wrapper and tried to use the interface directly:
[link](https://github.com/AKJAW/KMP-Natvie-Coroutines-Modularization-Issue/blob/main/ios/KaMPKitiOS/AppDelegate.swift)
```swift
let future = createPublisher(for: getTodoCount.invokeNative())

let cancellable = future.sink { completion in
    print("Received completion: \(completion)")
} receiveValue: { count in
    print("Received value: \(count)")
    if (count != nil){
        self.count = count as! TodoCount
    }
}
```

But it fails with the following error:
```
2022-02-04 08:31:38.374976+0100 KaMPKitiOS[1700:34628] -[Shared_kobjcc0 invokeNative]: unrecognized selector sent to instance 0x60000194d290
2022-02-04 08:31:38.419835+0100 KaMPKitiOS[1700:34628] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[Shared_kobjcc0 invokeNative]: unrecognized selector sent to instance 0x60000194d290'
```

It does generate the correct native function, but the function crashes the app:
```objc
__attribute__((swift_name("GetTodoCount")))
@protocol SharedGetTodoCount
@required
- (id<SharedFlow>)invoke __attribute__((swift_name("invoke()")));
- (SharedKotlinUnit *(^(^)(SharedKotlinUnit *(^)(SharedTodoCount *, SharedKotlinUnit *), SharedKotlinUnit *(^)(NSError * _Nullable, SharedKotlinUnit *)))(void))invokeNative __attribute__((swift_name("invokeNative()")));
@end;
```

I'm not sure if this is caused by the fact that the interface does not know what the underlying implementation is or it is related to something else.

## Light weight wrapper by interface delegation

Another solution I tried was using interface delegation, the wrapper is still written by hand but it's pretty concise and does not require updates when changing the interface:
[link](https://github.com/AKJAW/KMP-Natvie-Coroutines-Modularization-Issue/blob/d0109138d65295f97832663fc7b88f65b189e31a/kmm/todos/todos-count-api/src/iosMain/kotlin/co/touchlab/kmm/todos/count/api/domain/GetTodoCountIos.kt)
```kotlin
class GetTodoCountIos(
    private val getTodoCount: GetTodoCount
) : GetTodoCount by getTodoCount
```

[link](https://github.com/AKJAW/KMP-Natvie-Coroutines-Modularization-Issue/blob/d0109138d65295f97832663fc7b88f65b189e31a/ios/KaMPKitiOS/AppDelegate.swift)
But it also fails, but with a different error:
```
Terminating app due to uncaught exception 'NSGenericException', reason: '[SharedGetTodoCountIos invokeNative] can't be overridden: it is final'
```

The generated header file:
```objc
__attribute__((objc_subclassing_restricted))
__attribute__((swift_name("GetTodoCountIos")))
@interface SharedGetTodoCountIos : SharedBase <SharedGetTodoCount>
- (instancetype)initWithGetTodoCount:(id<SharedGetTodoCount>)getTodoCount __attribute__((swift_name("init(getTodoCount:)"))) __attribute__((objc_designated_initializer));
- (id<SharedFlow>)invoke __attribute__((swift_name("invoke()")));
@end;
```

Maybe it would be possible to extend it using an extension function?

## Normal wrapper

The only solution that did not crash was creating the wrapper and calling the methods on the interface:
[link](https://github.com/AKJAW/KMP-Natvie-Coroutines-Modularization-Issue/blob/a559f206b62556373b840509524524c9f7136449/kmm/todos/todos-count-api/src/iosMain/kotlin/co/touchlab/kmm/todos/count/api/domain/GetTodoCountIos.kt)
```kotlin
class GetTodoCountIos(
    private val getTodoCount: GetTodoCount
){

    fun invoke(): Flow<TodoCount> = getTodoCount()
}
```

With the following header:
```objc
__attribute__((objc_subclassing_restricted))
__attribute__((swift_name("GetTodoCountIos")))
@interface SharedGetTodoCountIos : SharedBase
- (instancetype)initWithGetTodoCount:(id<SharedGetTodoCount>)getTodoCount __attribute__((swift_name("init(getTodoCount:)"))) __attribute__((objc_designated_initializer));
- (id<SharedFlow>)invoke __attribute__((swift_name("invoke()")));
- (SharedKotlinUnit *(^(^)(SharedKotlinUnit *(^)(SharedTodoCount *, SharedKotlinUnit *), SharedKotlinUnit *(^)(NSError * _Nullable, SharedKotlinUnit *)))(void))invokeNative __attribute__((swift_name("invokeNative()")));
@end;
```

However this also didn't work as expected, because the flow is never collected (onEach, onComplete never called).

The repository to reproduce this is available here:
- [using interface directly](https://github.com/AKJAW/KMP-Natvie-Coroutines-Modularization-Issue/tree/8b5d0dce4f78defa1c9e5ca9ffc0ce95dd31d6c2)
- [using wrapper with property delefation](https://github.com/AKJAW/KMP-Natvie-Coroutines-Modularization-Issue/tree/d0109138d65295f97832663fc7b88f65b189e31a)
- [using a wrapper that just calls the underlying interface](https://github.com/AKJAW/KMP-Natvie-Coroutines-Modularization-Issue/tree/a559f206b62556373b840509524524c9f7136449)

**Comment by rickclephas** [comment] 2022-02-04 21:19
Thanks for the detailed report!
Just a small update on what I found so far (having some trouble running the reproduction project on a MBP with M1):

I was able to reproduce the `unrecognized selector` error when the interface and the implementation are in separate modules. So far I wasn't able to reproduce this when both are in the same module.

Wasn't able to reproduce the `can't be overridden` error yet.
However the generated native functions/properties are marked as `final` so that probably explains the error.
The final modifier makes sense for classes but not so much for interfaces 🙃.

The normal wrapper solution should work once you store the [cancellable](https://github.com/AKJAW/KMP-Natvie-Coroutines-Modularization-Issue/blob/a559f206b62556373b840509524524c9f7136449/ios/KaMPKitiOS/AppDelegate.swift#L110). 
Currently the cancellable will be deallocated at the end of `onAppear` which will immediately cancel the collection.

**Comment by rickclephas** [comment] 2022-02-04 21:26
Alright it looks like the root cause is that generated functions/properties are marked as `final`, which isn't valid inside an interface. I am no longer able to reproduce the `unrecognized selector` error once the generated function is marked as `open`.

I am going to try and do some more testing with your reproduction project to verify all the scenarios 😄.

**Comment by rickclephas** [comment] 2022-02-05 11:45
After updating some dependencies I was able to run the reproduction project and reproduce both errors.
I can confirm that both are caused by the `final` modality of the generated functions, once they are marked as `open` the errors disappear.

After that the only thing that's preventing the app from working correctly is the deallocation of the cancellable.
Was able to "fix" that with the following:

```diff
diff --git a/ios/KaMPKitiOS/AppDelegate.swift b/ios/KaMPKitiOS/AppDelegate.swift
index 2bcda2dbed96b74719c3bea86c024f458a2faf8b..213a5fe2f896fed028a4bac117ab08ec713194d5 100644
--- a/ios/KaMPKitiOS/AppDelegate.swift
+++ b/ios/KaMPKitiOS/AppDelegate.swift
@@ -91,6 +91,8 @@ struct TodosListView: View {
     }
 }
 
+var cancellable: AnyCancellable?
+
 struct CountView: View {
     
     private let getTodoCount = koin.get(objCClass: GetTodoCountIos.self) as! GetTodoCountIos
@@ -107,7 +109,7 @@ struct CountView: View {
             let future = createPublisher(for: getTodoCount.invokeNative())
 
             // Now use this future as you would any other
-            let cancellable = future.sink { completion in
+            cancellable = future.sink { completion in
                 print("Received completion: \(completion)")
             } receiveValue: { count in
                 print("Received value: \(count)")

```

**Closed** 2022-02-05 17:42 UTC

**Comment by rickclephas** [comment] 2022-02-05 20:32
Fix has been published in [v0.11.2](https://github.com/rickclephas/KMP-NativeCoroutines/releases/tag/v0.11.2)

**Comment by AKJAW** [comment] 2022-02-05 20:48
Thanks for the quick response and fix! 

You're right, after keeping a reference to the cancellable it works correctly (it shows that I'm an Android dev 😆)

I'll try the 0.11.2 version as soon as I can in our real project and let you know how that works out 😄

**Comment by AKJAW** [comment] 2022-02-08 11:54
For small logic everything seems to be working in our real project. The issue arises when we use ensureNeverFrozen.

I have 2 follow up questions (not sure if this is the best place):
1. Does this generation cause the classes / interfaces to be frozen? We have some places where we call ensureNeverFrozen() and regardless of the dispatcher the app crashes with a FreezingException. Would you require an example to investigate this?
2. What would be the best way to define custom scopes / dispatchers in the Interfaces?

Global property (which I think will be a singleton for the whole app lifecycle)
```kotlin

val scope = CoroutineScope(SupervisorJob() + Dispatchers.Unconfined)

interface TestingCoroutinesDispatcher {

    @NativeCoroutineScope
    private val coroutineScope: CoroutineScope
        get() = scope

    suspend fun initialize()
}
```

or creating a new scope on every get
```kotlin
interface TestingCoroutinesDispatcher {

    @NativeCoroutineScope
    private val coroutineScope: CoroutineScope
        get() = CoroutineScope(SupervisorJob() + Dispatchers.Unconfined)

    suspend fun initialize()
}
```

or something else?

**Comment by rickclephas** [comment] 2022-02-08 17:10
> Does this generation cause the classes / interfaces to be frozen?

Yeah in the non `-new-mm` versions most objects (like the Flow itself) are being frozen. 
Though if I am not mistaken this shouldn't freeze the class itself (unless the Flow captures a reference to it of course).

> What would be the best way to define custom scopes / dispatchers in the Interfaces?

That depends on the reason why you need a custom scope 😁.

In case you need access to the `Job` for a specific class (like in the [integration tests](https://github.com/rickclephas/KMP-NativeCoroutines/blob/c1b7821bfb822cdc458d5fae1a1939abb3e7b1e0/sample/shared/src/commonMain/kotlin/com/rickclephas/kmp/nativecoroutines/sample/tests/IntegrationTests.kt)) than you could just use a fixed scope inside the class itself.

If however you want to use a different Dispatcher than a global property like in your first example is a great choice.
Just keep in mind that with the old memory model you should annotate it with `@SharedImmutable`.
This is exactly how the default CoroutineScope is [implemented](https://github.com/rickclephas/KMP-NativeCoroutines/blob/c1b7821bfb822cdc458d5fae1a1939abb3e7b1e0/kmp-nativecoroutines-core/src/appleMain/kotlin/com/rickclephas/kmp/nativecoroutines/CoroutineScope.kt).

I can't really think of a scenario where you would need a different scope on each invocation.

Some more examples on how the CoroutineScope could be provided: https://github.com/rickclephas/KMP-NativeCoroutines/issues/34#issuecomment-1022935561
