### ISSUE TITLE
kotlin.IllegalStateException: Non-main native call error on iOS while using Apollo GraphQL

### ISSUE THREAD

**Issue by alexpresence** [rickclephas/KMP-NativeCoroutines#65] opened 2022-05-21 22:59 UTC
Greetings. 

Amazing project, well done to all. I'm having an issue on the iOS side when I subscribe to a flow which fetches data from the network using GraphQL. I'm using Apollo and Koin DI on the kotlin side. When running iOS, i see the following issue: 

`kotlin.IllegalStateException: Non-main native call`. 

Has anyone seen this before?

**Comment by rickclephas** [comment] 2022-05-22 08:36
The default completion handler functions (generated by Kotlin) must be invoked from the main thread.
However with KMP-NativeCoroutines that shouldn't be necessary.
Could you share the full stacktrace?

**Comment by joreilly** [comment] 2022-05-25 18:04
fwiw the following sample is using Apollo and KMP-NativeCoroutines

https://github.com/joreilly/StarWars

**Comment by rickclephas** [comment] 2022-06-25 17:14
I am going to close this as I am unable to reproduce this without more information.

**Closed by rickclephas** 2022-06-25 17:14 UTC
